global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - preview_generation.rules.yml

scrape_configs:
  - job_name: optimal-build-backend
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:8000
