apiVersion: v1
kind: Service
metadata:
  name: {{ include "optimal-build.fullname" . }}-backend
  labels:
    {{- include "optimal-build.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "optimal-build.backend.selectorLabels" . | nindent 4 }}
